init:
  - git submodule init
  - git submodule update --init --recursive

# reset is not yet supported
reset:
  - git submodule deinit -f .

# dependent repos, not yet implemented
repos:
  - name: ipbus
    type: git
    path: https://github.com/ipbus/ipbus-firmware.git
    branch: v1.9
